### ISSUE TITLE
Issue 1: standardize desired column

### ISSUE THREAD

**Issue by junxianxiao** [dsi-principles-prog/midterm-junxianxiao#1]
Standardizing numeric data is necessary in data analysis. In this function we want to standardize the given column and put it into a new column whose name can change as the given column changes. For example, when we type standardize(Hostel,cleanliness,'cleanliness'), we hope the name of new column to be cleanliness_std. You may also get some detail information chunck named function 3: standardize column, which is in the file 30-feature-engineering.rmd.

input: dataset, column, column name
output: create a new column which standardizes the given column
target column: actually all of the column including score need to be standardized, but here we can just standardize one of those columns named summary.score
functions you might need: mutate( ), column - mean(column))/sd(column), names( )[ ]

**Comment by Teddy-Weaver** [comment]
@junxianxiao  - Please give me write access to the repo (under settings, collaborator).

Which column should be standardized? It is not clear from the instructions. I have done cleanliness in the meantime.

**Comment by Teddy-Weaver** [comment]
Issue completed
